services:
  app:
    container_name: message-broker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
    restart: unless-stopped